version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: members-admin
      POSTGRES_USER: jarad
      POSTGRES_PASSWORD: Bmw335iE92M4!
